apiVersion: v1
kind: Pod
metadata:
  name: existing-nfs-share-pod
spec:
  containers:
    - name: web-server
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: existing-nfs-share-pvc
        readOnly: false
