apiVersion: v1
kind: Secret
metadata:
  name: csi-manila-secrets
  namespace: default
stringData:
  # Mandatory
  os-authURL: "some-auth-url"
  os-region: "some-region"

  # Authentication using user credentials
  os-userName: "some-username"
  os-password: "some-password"
  os-projectName: "some-project-name"
  os-domainID: "some-domain-id"

  # Authentication using trustee credentials
  os-trustID: "some-trust-id"
  os-trusteeID: "some-trustee-id"
  os-trusteePassword: "some-trustee-password"
