apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openstack-manila-csi.serviceAccountName.controllerplugin" . }}
  labels:
    app: {{ include "openstack-manila-csi.name" . }}
    chart: {{ include "openstack-manila-csi.chart" . }}
    component: {{ .Values.controllerplugin.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
