kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "openstack-manila-csi.nodeplugin.fullname" . }}
  labels:
    {{- include "openstack-manila-csi.nodeplugin.labels" .  | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.manila.csi.openstack.org/aggregate-to-nodeplugin-{{ include "openstack-manila-csi.name" . }}: "true"
rules: []
