kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "openstack-manila-csi.nodeplugin.fullname" . }}
  labels:
    {{- include "openstack-manila-csi.nodeplugin.labels" .  | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "openstack-manila-csi.serviceAccountName.nodeplugin" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "openstack-manila-csi.nodeplugin.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
