apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openstack-manila-csi.serviceAccountName.nodeplugin" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openstack-manila-csi.nodeplugin.labels" .  | nindent 4 }}
