apiVersion: v1
entries:
  openstack-cloud-controller-manager:
  - apiVersion: v1
    appVersion: latest
    created: "2022-07-22T19:09:27.346238051+03:00"
    description: Openstack Cloud Controller Manager Helm Chart
    digest: 6fa7de1bf36d7965e6dd0d107607f9d7aad077c813850d888c22c2f1030409ce
    home: https://github.com/kubernetes/cloud-provider-openstack
    icon: https://object-storage-ca-ymq-1.vexxhost.net/swift/v1/6e4619c416ff4bd19e1c087f27a43eea/www-images-prod/openstack-logo/OpenStack-Logo-Vertical.png
    name: openstack-cloud-controller-manager
    urls:
    - https://github.com/zakthan/cloud-provider-openstack/raw/master/openstack-cloud-controller-manager-1.3.0.tgz
    version: 1.3.0
generated: "2022-07-22T19:09:27.344488873+03:00"
