{{- if or .Values.storageClass.enabled .Values.storageClass.delete.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cinder-sc-delete
  {{- if .Values.storageClass.delete.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: cinder.csi.openstack.org
reclaimPolicy: Delete
allowVolumeExpansion: {{ .Values.storageClass.delete.allowVolumeExpansion }}
{{- end }}
{{- if or .Values.storageClass.enabled .Values.storageClass.retain.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cinder-sc-retain
  {{- if .Values.storageClass.retain.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: cinder.csi.openstack.org
reclaimPolicy: Retain
allowVolumeExpansion: {{ .Values.storageClass.retain.allowVolumeExpansion }}
{{- end }}