ARG DEBIAN_ARCH=amd64
FROM k8s.gcr.io/build-image/debian-base-${DEBIAN_ARCH}:v2.1.3

ARG ARCH=amd64

# Install e4fsprogs for format
RUN clean-install ca-certificates e2fsprogs mount xfsprogs udev

ADD cinder-csi-plugin-${ARCH} /bin/cinder-csi-plugin
