apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-manila-cephfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-manila-cephfs

