apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  labels:
    app: demo
spec:
  ports:
    - name: filemanager
      port: 80
  selector:
    app: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-depl
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo-filebrowser
        image: hacdias/filebrowser
        args: ["--port", "80", "--database", "/database.db", "--scope", "/srv", "--no-auth"]
        ports:
          - containerPort: 80
        volumeMounts:
          - name: cephfs-mount
            mountPath: /srv
      volumes:
        - name: cephfs-mount
          persistentVolumeClaim:
            claimName: manila-csicephfs-pvc
            readOnly: false
