kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: manila-csicephfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: manila-csicephfs-share
