apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshotClass
metadata:
  name: csi-manila-snapclass
snapshotter: manila.csi.openstack.org
parameters:
  csi.storage.k8s.io/snapshotter-secret-name: manila-devstack-secrets
  csi.storage.k8s.io/snapshotter-secret-namespace: default
