apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: new-nfs-share-snap
spec:
  volumeSnapshotClassName: csi-manila-nfs
  source:
    persistentVolumeClaimName: new-nfs-share-pvc
