apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshotClass
metadata:
  name: csi-manila-nfs
snapshotter: nfs.manila.csi.openstack.org
parameters:
  csi.storage.k8s.io/snapshotter-secret-name: csi-manila-secrets
  csi.storage.k8s.io/snapshotter-secret-namespace: default
