apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-manila-nfs
driver: nfs.manila.csi.openstack.org
deletionPolicy: Delete
parameters:
  csi.storage.k8s.io/snapshotter-secret-name: csi-manila-secrets
  csi.storage.k8s.io/snapshotter-secret-namespace: default
