ARG REPO_LOCATION=docker.io/
ARG ALPINE_ARCH=amd64
FROM ${REPO_LOCATION}${ALPINE_ARCH}/alpine:3.11

ARG ARCH=amd64

RUN apk add --no-cache ca-certificates jq curl

ADD manila-csi-plugin-${ARCH} /bin/manila-csi-plugin
