apiVersion: v1
appVersion: v1.36.0
description: Manila CSI Chart for OpenStack
name: openstack-manila-csi
version: 2.37.0-dev
home: https://github.com/kubernetes/cloud-provider-openstack
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
maintainers:
- name: stephenfin
  email: stephenfin@redhat.com
