ARG REPO_LOCATION=docker.io/
ARG ALPINE_ARCH=amd64
FROM ${REPO_LOCATION}${ALPINE_ARCH}/alpine:3.11
LABEL maintainers="Kubernetes Authors"
LABEL description="Barbican KMS Plugin"

ARG ARCH=amd64
ADD barbican-kms-plugin-${ARCH} /bin/barbican-kms-plugin
