apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: new-nfs-share-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-manila-nfs-az

