apiVersion: v1
kind: Pod
metadata:
  name: manila-cephfs-pod
spec:
  containers:
    - name: test
      image: busybox
      command: [ "/bin/sh", "-c", "trap : TERM INT; (while true; do sleep 1000; done) & wait" ]
      volumeMounts:
        - name: cephfs-share
          mountPath: /mnt
  volumes:
    - name: cephfs-share
      persistentVolumeClaim:
        claimName: manila-cephfs-pvc
        readOnly: false
