kind: Service
apiVersion: v1
metadata:
  name: csi-attacher
  labels:
    app: csi-attacher
spec:
  selector:
    app: csi-attacher
  ports:
    - name: dummy
      port: 12345
---
kind: Service
apiVersion: v1
metadata:
  name: csi-provisioner
  labels:
    app: csi-provisioner
spec:
  selector:
    app: csi-provisioner
  ports:
    - name: dummy
      port: 12345
---
kind: Service
apiVersion: v1
metadata:
  name: manila-provisioner
  labels:
    app: manila-provisioner
spec:
  selector:
    app: manila-provisioner
  ports:
    - name: dummy
      port: 12345
