apiVersion: apps/v1
kind: Deployment
metadata:
  name: manila-provisioner
  labels:
    app: manila-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manila-provisioner
  template:
    metadata:
      labels:
        app: manila-provisioner
    spec:
      serviceAccount: manila-provisioner
      containers:
      - name: manila-provisioner
        image: docker.io/k8scloudprovider/manila-provisioner:latest
        imagePullPolicy: IfNotPresent
        args: [ "--provisioner=manila-provisioner" ]
