---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver: "cinder.io/cinder-flex-volume-driver"
      fsType: "ext4"
      options:
        volumeID: "$VOLUME_ID"
        cinderConfig: "/etc/kubernetes/cloud-config"
